inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/*'
